# Generated by Django 5.0.10 on 2025-01-03 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('event_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10, verbose_name='Event Type')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='event_flyers/', verbose_name='Event Flyer')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('event_date', models.DateTimeField(verbose_name='Event Date & Time')),
                ('ticket_link', models.URLField(blank=True, null=True, verbose_name='Ticket/Registration Link')),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo Code')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=30, verbose_name='Approval Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Organizer')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_date'],
            },
        ),
    ]
